export * from './Hero'
export * from './AboutBitmor'
export * from './JustLikeMortgage'
export * from './BorrowerLender'
export * from './Testimonials'
export * from './FAQs'
export * from './CTABanner'
// export * from './Stats'
// export * from './Borrowers'
// export * from './Lenders'
// export * from './WhyBitcoin'
// export * from './Team'
