export const MY_BORROWINGS = [
  {
    id: 1,
    loanAmount: 0.232,
    loanHealth: 50,
    loanStatus: 'Active',
    outstandingAmount: 1000,
    btcReceived: 1000,
    principalPaid: 1000,
    interestPaid: 1000,
  },
  {
    id: 2,
    loanAmount: 0.456,
    loanHealth: 80,
    loanStatus: 'Active',
    outstandingAmount: 2000,
    btcReceived: 2000,
    principalPaid: 500,
    interestPaid: 300,
  },
  {
    id: 3,
    loanAmount: 0.189,
    loanHealth: 20,
    loanStatus: 'Active',
    outstandingAmount: 800,
    btcReceived: 800,
    principalPaid: 200,
    interestPaid: 150,
  },
  {
    id: 7,
    loanAmount: 1.321,
    loanHealth: 100,
    loanStatus: 'Closed',
    outstandingAmount: 0,
    btcReceived: 1500,
    principalPaid: 1500,
    interestPaid: 250,
  },
  {
    id: 4,
    loanAmount: 0.512,
    loanHealth: 100,
    loanStatus: 'Defaulted',
    defaultDuration: '1 Month',
    outstandingAmount: 2500,
    btcReceived: 2500,
    principalPaid: 0,
    interestPaid: 0,
  },
  {
    id: 6,
    loanAmount: 2.532,
    loanHealth: 100,
    loanStatus: 'Liquidated',
    outstandingAmount: 1200,
    btcReceived: 1200,
    principalPaid: 0,
    interestPaid: 0,
  },
  {
    id: 8,
    loanAmount: 0.398,
    loanHealth: 100,
    loanStatus: 'Active',
    outstandingAmount: 1800,
    btcReceived: 1800,
    principalPaid: 600,
    interestPaid: 200,
  },
]

export const SORTINGS = [
  { key: 'newest', label: 'Newest Loans First' },
  { key: 'oldest', label: 'Oldest Loans First' },
  { key: 'amount-high', label: 'Highest Loan Amount' },
  { key: 'amount-low', label: 'Lowest Loan Amount' },
  { key: 'health-high', label: 'Healthiest Loans First' },
  { key: 'health-low', label: 'At-Risk Loans First' },
  { key: 'outstanding-high', label: 'Highest Outstanding Balance' },
  { key: 'outstanding-low', label: 'Lowest Outstanding Balance' },
  { key: 'received-high', label: 'Most BTC Received' },
  { key: 'received-low', label: 'Least BTC Received' },
  { key: 'paid-high', label: 'Most Principal Paid' },
  { key: 'paid-low', label: 'Least Principal Paid' },
] as const

export const TIME_PERIOD_AND_INTEREST_RATES = [
  {
    timePeriod: '6',
    interestRate: '7',
  },
  {
    timePeriod: '12',
    interestRate: '10',
  },
  {
    timePeriod: '18',
    interestRate: '15',
  },
] as const
